name: Build Translated Markdown

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'l10n_main' }}
    steps:
      - name: Checkout Build
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: build

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Prepare Environment
        run: |
          sudo apt-get install zsh
          pip3 install --upgrade mdpo

      - name: Update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin main
          git merge origin/main --no-edit

      - name: Build
        run: |
          zsh build.sh zh_TW

      - name: Commit & Push
        run: |
          git add .
          git commit -m "Build fresh translations"
          git push origin build
