name: Update Translations Template

on:
  push:
    paths:
      - 'docs/**'
      - update_template.py

jobs:
  update_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        uses: actions/checkout@v2

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.10' 

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.3.2'

      - name: Prepare Environment
        run: |
          poetry install

      - name: Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Build
        run: |
          poetry run python3 update_template.py

      - name: Commit & Push
        run: |
          git add .
          git commit -m "Update template"
          git push origin main
