name: Update Translations Template

on:
  push:
    branches:
      - main

jobs:
  update_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        uses: actions/checkout@v2

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Prepare Environment
        run: |
          sudo apt-get install po4a zsh

      - name: Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Build
        run: |
          zsh update_template.sh

      - name: Commit & Push
        run: |
          git add .
          git commit -m "Update template"
          git push origin main
