name: Update Translations Template

on:
  push:
    paths:
      - 'docs/**'
      - update_template.py

jobs:
  update_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        uses: actions/checkout@v2

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Prepare Environment
        run: |
          pip3 install -r ./requirements.txt

      - name: Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Build
        run: |
          python3 update_template.py

      - name: Commit & Push
        run: |
          git add .
          git commit -m "Update template"
          git push origin main
